server :
  port : 8080
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    publisher-confirm-type: simple
    publisher-returns: true